version: '3.4'

services:
  samba:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: samba
    restart: unless-stopped
    environment:
      - USERID=${PUID}
      - GROUPID=${PGID}
      - TZ=${TZ}
    network_mode: "host"
    volumes:
      - ${SHARE1PATH}:${SHARE1PATH}
      - ${SHARE2PATH}:${SHARE2PATH}
    command:
      -w "HOME"
      -u "${USERNAME};${PASSWORD};;${USERNAME}"
      -s "${SHARE1NAME};${SHARE1PATH};yes;no;no;;;;${SHARE1NAME}"
      -s "${SHARE2NAME};${SHARE2PATH};yes;no;no;;;;${SHARE2NAME}"
      -g "netbios name = ${NETBIOSNAME}"
      -n
      -p
      -r
      -g "server string = dockerized CIFS SMB server"
      -g "ea support = yes"
      -g "fruit:advertise_fullsync = true"
      -g "durable handles = yes"
      -g "kernel oplocks = no"
      -g "kernel share modes = no"
      -g "posix locking = no"
      -g "inherit acls = yes"
      -g "idmap config * :range = 3000-7999"
